### ISSUE TITLE
createDefaultCallbacksProviderWithIotCertificate root ca cert not optional

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#278]
In createDefaultCallbacksProviderWithIotCertificate,
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L413
It mentioned that CA Cert path is "IN/OPT" which is optional.
But it is not.
See  https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/source/IotAuthCallback.c#L25, it will return STATUS_NULL_ARG if that is not set.

**Comment by unicornss** [comment]
Hi @ek9852 

Thanks for notifying; we will update the documentation block as applicable to the type signature.

**Comment by MushMal** [comment]
On the second thought, this should really be an OPT param. We will fix this in the upcoming releases

**Comment by ek9852** [comment]
Yep, I agree.

**Comment by MushMal** [comment]
Fixed! THANK YOU! The latest release v2.1.0

**Comment by ek9852** [comment]
@MushMal It is not fixed. Pls see :
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/2.1.0/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L281

**Comment by MushMal** [comment]
Just a NOTE: the cert path is a mandatory param (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L279) whereas the caCertPath is not (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L281)
